package search.card;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import commons.Commons;
import commons.models.CardListTableModel;
import entity.CardEntity;
import entity.EditionEntity;
import entity.RaceEntity;
import entity.TypeEntity;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

/**
 * Created by wemstar on 15.12.13.
 */
public class SearchCardV {
    private SearchCardC controller;
    private SearchCardM model;
    private JTable tSearchResult;
    private JTextField tfName;
    private JComboBox cbType;
    private JComboBox cbRace;
    private JComboBox cbEdition;
    private JPanel mainPanel;
    private JButton bSearch;


    public SearchCardV() {
        initializeComponents();
        bSearch.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.searchCard();
            }
        });
        tSearchResult.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent me) {

                if (me.getClickCount() == 2) {
                    JTable table = (JTable) me.getSource();
                    Point p = me.getPoint();
                    int row = table.rowAtPoint(p);
                    CardEntity entity = ((CardListTableModel) (table.getModel())).getRowAt(row);
                    controller.cardDetail(entity);
                }
            }
        });
    }


    private void initializeComponents() {

        cbRace.setModel(new DefaultComboBoxModel(Commons.raceList.toArray()));
        cbEdition.setModel(new DefaultComboBoxModel(Commons.editionList.toArray()));
        cbType.setModel(new DefaultComboBoxModel(Commons.typeList.toArray()));
        tSearchResult.setModel(new CardListTableModel());

    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public void setModel(SearchCardM model) {
        this.model = model;
    }

    public SearchCardM getModel() {
        return model;
    }

    public String getName() {
        return tfName.getText();
    }

    public RaceEntity getRace() {
        return (RaceEntity) cbRace.getSelectedItem();
    }

    public TypeEntity getType() {
        return (TypeEntity) cbType.getSelectedItem();
    }

    public EditionEntity getEdition() {
        return (EditionEntity) cbEdition.getSelectedItem();
    }

    public List<CardEntity> getCardList() {
        return ((CardListTableModel) (tSearchResult.getModel())).getCardList();
    }

    public void setName(String name) {
        tfName.setText(name);
    }

    public void setRace(RaceEntity race) {
        cbRace.setSelectedItem(race);
    }

    public void setType(TypeEntity type) {
        cbType.setSelectedItem(type);
    }

    public void setEdition(EditionEntity edition) {
        cbEdition.setSelectedItem(edition);
    }

    public void setCardList(List<CardEntity> cardList) {
        ((CardListTableModel) (tSearchResult.getModel())).setCardList(cardList);
        tSearchResult.updateUI();

    }

    public void setController(SearchCardC controller) {
        this.controller = controller;
    }

    public void setActiveControl(boolean activeControl) {
        bSearch.setEnabled(activeControl);
        tfName.setEnabled(activeControl);
        cbType.setEnabled(activeControl);
        cbRace.setEnabled(activeControl);
        cbEdition.setEnabled(activeControl);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(5, 3, new Insets(0, 0, 0, 0), -1, -1));
        tfName = new JTextField();
        mainPanel.add(tfName, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Nazwa");
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Typ");
        mainPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbType = new JComboBox();
        mainPanel.add(cbType, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbRace = new JComboBox();
        mainPanel.add(cbRace, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Rasa");
        mainPanel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbEdition = new JComboBox();
        mainPanel.add(cbEdition, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Edycja");
        mainPanel.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bSearch = new JButton();
        bSearch.setText("Szukaj");
        mainPanel.add(bSearch, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, new GridConstraints(0, 2, 5, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tSearchResult = new JTable();
        scrollPane1.setViewportView(tSearchResult);
        label2.setLabelFor(cbType);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
