package statistic.deck;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * Created by wemstar on 26.12.13.
 */
public class DeckStatisticV {
    private JPanel mainPanel;
    private JPanel panelOne;
    private JPanel panelTwo;
    private JPanel panelThere;
    private JPanel panelFour;
    private DeckStatisticM model;
    private DeckStatisticC controller;

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }

    public JPanel getPanelOne() {
        return panelOne;
    }

    public void setPanelOne(JPanel panelOne) {
        this.panelOne = panelOne;
    }

    public JPanel getPanelTwo() {
        return panelTwo;
    }

    public void setPanelTwo(JPanel panelTwo) {
        this.panelTwo = panelTwo;
    }

    public JPanel getPanelThere() {
        return panelThere;
    }

    public void setPanelThere(JPanel panelThere) {
        this.panelThere = panelThere;
    }

    public JPanel getPanelFour() {
        return panelFour;
    }

    public void setPanelFour(JPanel panelFour) {
        this.panelFour = panelFour;
    }

    public DeckStatisticM getModel() {
        return model;
    }

    public void setModel(DeckStatisticM model) {
        this.model = model;
    }

    public DeckStatisticC getController() {
        return controller;
    }

    public void setController(DeckStatisticC controller) {
        this.controller = controller;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelOne = new JPanel();
        panelOne.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panelOne, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelTwo = new JPanel();
        panelTwo.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panelTwo, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelThere = new JPanel();
        panelThere.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panelThere, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelFour = new JPanel();
        panelFour.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panelFour, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
